url: ""
baseurl: ""
title: "Antiuniversity Now"
plugins:
  - jekyll-datapage-generator
page_gen-dirs: true
sass:
    sass_dir: _sass
    style: compressed
page_gen:
  - data: "events-2021"
    template: "event"
    name: "title"
    dir: "events"

  - data: "events-2020"
    template: "event"
    name: "title"
    dir: "events"

  - data: "events-2019"
    template: "event"
    name: "title"
    dir: "events"

  - data: "events-2018"
    template: "event"
    name: "title"
    dir: "events"

  - data: "events-2017"
    template: "event"
    name: "title"
    dir: "events"

  - data: "events-2016"
    template: "event"
    name: "title"
    dir: "events"

  - data: "events-2015"
    template: "event"
    name: "title"
    dir: "events"
